---
- name: Manage Windmill Workers
  hosts: windmill_workers
  gather_facts: yes

  vars:
    operation: "{{ op | default('status') }}"
    worker: "{{ worker_name | default('') }}"
    git_branch: "{{ branch | default('main') }}"

  tasks:
    - name: Check if windmill directory exists
      stat:
        path: "{{ windmill_path }}"
      register: windmill_dir

    - name: Fail if windmill directory not found
      fail:
        msg: "Windmill directory not found at {{ windmill_path }} on {{ inventory_hostname }}"
      when: not windmill_dir.stat.exists

    - name: Check if windmill.sh script exists
      stat:
        path: "{{ windmill_path }}/windmill.sh"
      register: windmill_script

    - name: Fail if windmill.sh script not found
      fail:
        msg: "windmill.sh script not found at {{ windmill_path }}/windmill.sh on {{ inventory_hostname }}"
      when: not windmill_script.stat.exists

    - name: Execute windmill command (all workers)
      shell: |
        cd {{ windmill_path }}
        ./windmill.sh {{ operation }}
      register: windmill_all_output
      when: worker == "" and operation != "update"

    - name: Execute windmill command (specific worker)
      shell: |
        cd {{ windmill_path }}
        ./windmill.sh {{ operation }} {{ worker }}
      register: windmill_worker_output
      when: worker != "" and operation != "update"

    - name: Git pull to update code
      shell: |
        cd {{ windmill_path }}
        git pull origin {{ git_branch }}
      register: git_output
      when: operation == "update"

    - name: Display git update output
      debug:
        msg: |
          === {{ inventory_hostname }} Git Update ===
          {{ git_output.stdout }}
          {% if git_output.stderr %}
          STDERR: {{ git_output.stderr }}
          {% endif %}
      when: operation == "update"

    - name: Display windmill output (all workers)
      debug:
        msg: "{{ windmill_all_output.stdout | regex_replace('\\x1b\\[[0-9;]*m', '') | split('\n') }}"
      when: operation != "update" and windmill_all_output is defined and windmill_all_output.stdout is defined

    - name: Display windmill output (specific worker)
      debug:
        msg: "{{ windmill_worker_output.stdout | regex_replace('\\x1b\\[[0-9;]*m', '') | split('\n') }}"
      when: operation != "update" and windmill_worker_output is defined and windmill_worker_output.stdout is defined

    - name: Check for windmill errors (all workers)
      fail:
        msg: "Command failed on {{ inventory_hostname }}: {{ windmill_all_output.stderr }}"
      when: windmill_all_output is defined and windmill_all_output.rc is defined and windmill_all_output.rc != 0

    - name: Check for windmill errors (specific worker)
      fail:
        msg: "Command failed on {{ inventory_hostname }}: {{ windmill_worker_output.stderr }}"
      when: windmill_worker_output is defined and windmill_worker_output.rc is defined and windmill_worker_output.rc != 0